import type { PlatformConfig } from '@vlp/member-ui'

export const wlvlpConfig: PlatformConfig = {
  brandName: 'Website Lotto',
  brandAbbrev: 'WLVLP',
  brandColor: '#00D4FF',
  brandSubtitle: 'Template Marketplace',
  logoText: 'WL',
  apiBaseUrl: 'https://api.virtuallaunch.pro',
  posthog: {
    apiKey: 'phc_o5nTrNkxc37W2G9PXFL8peXMjWzdjo5d2HSjE5XzggkY',
    apiHost: 'https://us.i.posthog.com',
    autocapture: true,
    capturePageview: true,
    capturePageleave: true,
    disabledInDev: false,
  },
  calBookingNamespace: 'wlvlp-support',
  calBookingSlug: 'tax-monitor-pro/wlvlp-support',
  calIntroNamespace: 'wlvlp-intro',
  calIntroSlug: 'tax-monitor-pro/wlvlp-intro',
  navSections: [
    {
      title: 'WORKSPACE',
      items: [
        { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
        { label: 'My Sites', href: '/dashboard/sites', icon: 'Globe' },
        { label: 'Hosting', href: '/dashboard/hosting', icon: 'Server' },
        { label: 'Voting', href: '/dashboard/voting', icon: 'ThumbsUp' },
        { label: 'Templates', href: '/', icon: 'LayoutGrid' },
        { label: 'Scratch', href: '/scratch', icon: 'Ticket' },
      ],
    },
    {
      title: 'EARNINGS',
      items: [
        { label: 'Affiliate', href: '/dashboard/affiliate', icon: 'Link2' },
        { label: 'Bidding', href: '/dashboard/bidding', icon: 'Gavel' },
        { label: 'Winning', href: '/dashboard/winning', icon: 'Trophy' },
      ],
    },
    {
      title: 'SETTINGS',
      items: [
        { label: 'Account', href: '/dashboard/account', icon: 'Settings' },
        { label: 'Profile', href: '/dashboard/profile', icon: 'User' },
        { label: 'Support', href: '/dashboard/support', icon: 'LifeBuoy' },
        { label: 'Usage', href: '/dashboard/usage', icon: 'Activity' },
      ],
    },
  ],
  routes: {
    home: '/',
    signIn: '/sign-in',
    signOut: '/sign-in',
    dashboard: '/dashboard',
    account: '/dashboard/account',
    profile: '/dashboard/profile',
    support: '/dashboard/support',
  },
  businessInfo: {
    legalEntity: 'Lenore, Inc.',
    address: {
      line1: '1175 Avocado Avenue',
      line2: 'Suite 101 PMB 1010',
      city: 'El Cajon',
      state: 'CA',
      zip: '92020',
    },
    phone: '619-800-5457',
    supportEmail: 'outreach@virtuallaunch.pro',
  },
  marketing: {
    tagline: 'Website marketplace',
    summary: 'Win, bid on, or buy professionally designed websites — ready to launch with your brand.',
    ctaLabel: 'Free Ticket',
    ctaPath: '/scratch',
    megaMenu: {
      discover: [
        { label: 'About', href: '/about', description: 'Why Website Lotto exists' },
        { label: 'Contact', href: '/contact', description: 'Talk to our team or start intake' },
        { label: 'Site Hosting FAQ', href: '/support', description: 'How hosting and domains work' },
      ],
      explore: [
        { label: 'Features', href: '/features' },
        { label: 'How It Works', href: '/how-it-works' },
        { label: 'Pricing', href: '/pricing' },
        { label: 'Help Center', href: '/support' },
        { label: 'Template Gallery', href: '/' },
      ],
      toolsExtras: [
        { label: 'Template Gallery', href: '/' },
        { label: 'Before/After Preview', href: '/' },
        { label: 'Design Tips', href: '/support' },
        { label: 'Free Scratch Ticket', href: '/scratch' },
      ],
      ctaText: 'Want a professional website without building one yourself?',
      ctaMagnetLabel: 'Try a Free Scratch Ticket',
      ctaMagnetPath: '/scratch',
    },
    footerResources: [
      { label: 'Free Scratch Ticket', href: '/scratch' },
      { label: 'Affiliate Program', href: '/affiliate' },
      { label: 'Virtual Launch Pro', href: 'https://virtuallaunch.pro', external: true },
      { label: 'Tax Monitor Pro', href: 'https://taxmonitor.pro', external: true },
      { label: 'Developers VLP', href: 'https://developers.virtuallaunch.pro', external: true },
    ],
    footerLegal: [
      { label: 'Privacy', href: '/legal/privacy' },
      { label: 'Refund', href: '/legal/refund' },
      { label: 'Terms', href: '/legal/terms' },
    ],
    footerTagline: 'Website marketplace',
  },
}
