export interface TemplateEntry {
  slug: string;
  title: string;
  categories: string[];
}

export const TEMPLATES: TemplateEntry[] = [
  { slug: 'abandoned-places', title: 'Abandoned Places', categories: ['Destinations'] },
  { slug: 'adhd-tips', title: 'Adhd Tips', categories: ['Learning'] },
  { slug: 'ai-voice-cloning', title: 'Ai Voice Cloning', categories: ['Services', 'Trending'] },
  { slug: 'alien-worlds', title: 'Alien Worlds', categories: ['Cosmos'] },
  { slug: 'anime-vibes', title: 'Anime Vibes', categories: ['Art'] },
  { slug: 'apex-billionnaire-tax-structures', title: 'Apex Billionnaire Tax Structures', categories: ['Services'] },
  { slug: 'architecture-that-smooth', title: 'Architecture That Smooth', categories: ['Art', 'Services'] },
  { slug: 'baby-tiny-wins', title: 'Baby Tiny Wins', categories: ['Family'] },
  { slug: 'ballet-moves', title: 'Ballet Moves', categories: ['Art', 'Entertainment'] },
  { slug: 'balloons-are-us', title: 'Balloons Are Us', categories: ['Hobby', 'Holidays'] },
  { slug: 'barbers-cut', title: 'Barbers Cut', categories: ['Hair'] },
  { slug: 'barber-shop-luxury', title: 'Barber Shop Luxury', categories: ['Hair', 'Mood', 'Services'] },
  { slug: 'bingo-time', title: 'Bingo Time', categories: ['Events', 'Hobby'] },
  { slug: 'basketball-life', title: 'Basketball Life', categories: ['Sports'] },
  { slug: 'beach-glow', title: 'Beach Glow', categories: ['Travel'] },
  { slug: 'bear-country', title: 'Bear Country', categories: ['Animals'] },
  { slug: 'bee-stitch', title: 'Bee Stitch', categories: ['Animals'] },
  { slug: 'biology-upgrade-engine', title: 'Biology Upgrade Engine', categories: ['Beauty', 'Fitness', 'Services'] },
  { slug: 'brand-mood', title: 'Brand Mood', categories: ['Brand', 'Fame', 'Mood'] },
  { slug: 'business-tax-strategy-engineers', title: 'Business Tax Strategy Engineers', categories: ['Services'] },
  { slug: 'candle-light-the-mood', title: 'Candle Light The Mood', categories: ['Home', 'Mood'] },
  { slug: 'canvas-current', title: 'Canvas Current', categories: ['Art', 'Home'] },
  { slug: 'card-decks', title: 'Card Decks', categories: ['Hobby'] },
  { slug: 'calendars-unite', title: 'Calendars Unite', categories: ['Home'] },
  { slug: 'carpet-palace', title: 'Carpet Palace', categories: ['Home'] },
  { slug: 'cars-beyond', title: 'Cars Beyond', categories: ['Cars'] },
  { slug: 'casino-time', title: 'Casino Time', categories: ['Entertainment', 'Hobby'] },
  { slug: 'celebrities-around', title: 'Celebrities Around', categories: ['Fame', 'Lifestyle'] },
  { slug: 'ceramic-factory', title: 'Ceramic Factory', categories: ['Art', 'Hobby'] },
  { slug: 'christmas-home-glow', title: 'Christmas Home Glow', categories: ['Holidays'] },
  { slug: 'cinema-rush', title: 'Cinema Rush', categories: ['Movies'] },
  { slug: 'cinematic-caves', title: 'Cinematic Caves', categories: ['Adventure'] },
  { slug: 'circus-is-here', title: 'Circus Is Here', categories: ['Entertainment'] },
  { slug: 'clean-sweep', title: 'Clean Sweep', categories: ['Services'] },
  { slug: 'clear-ledger-bookkeeping', title: 'Clear Ledger Bookkeeping', categories: ['Services'] },
  { slug: 'clean-slate-digital', title: 'Clean Slate Digital', categories: ['Services', 'Trending'] },
  { slug: 'clip-scale-studio', title: 'Clip Scale Studio', categories: ['Services', 'Trending'] },
  { slug: 'close-rate-tax', title: 'Close Rate Tax', categories: ['Services'] },
  { slug: 'coffee-please', title: 'Coffee Please', categories: ['Beverages'] },
  { slug: 'comedy-clubs-open', title: 'Comedy Clubs Open', categories: ['Entertainment'] },
  { slug: 'construction-junction', title: 'Construction Junction', categories: ['Services'] },
  { slug: 'cornhole-fun', title: 'Cornhole Fun', categories: ['Sports'] },
  { slug: 'cosmic-visuals', title: 'Cosmic Visuals', categories: ['Cosmos'] },
  { slug: 'cosmetic-glam-vibe', title: 'Cosmetic Glam Vibe', categories: ['Cosmetics'] },
  { slug: 'creator-frame', title: 'Creator Frame', categories: ['Services'] },
  { slug: 'credit-repair', title: 'Credit Repair', categories: ['Services'] },
  { slug: 'criminal-attorney', title: 'Criminal Attorney', categories: [] },
  { slug: 'criminal-defense-attorney', title: 'Criminal Defense Attorney', categories: ['Legal', 'Services'] },
  { slug: 'criminal-tax-defense', title: 'Criminal Tax Defense', categories: ['Legal', 'Services'] },
  { slug: 'daily-prompts', title: 'Daily Prompts', categories: ['Prompts'] },
  { slug: 'deep-sea-diving', title: 'Deep Sea Diving', categories: ['Hobby'] },
  { slug: 'demolition-services', title: 'Demolition Services', categories: ['Services'] },
  { slug: 'dental-office-with-glow', title: 'Dental Office With Glow', categories: ['Services'] },
  { slug: 'dessert-ebook', title: 'Dessert Ebook', categories: ['Food'] },
  { slug: 'digital-art-vault', title: 'Digital Art Vault', categories: ['Art'] },
  { slug: 'digital-event-engine', title: 'Digital Event Engine', categories: ['Trending', 'Services'] },
  { slug: 'digital-product-experience', title: 'Digital Product Experience', categories: ['Art'] },
  { slug: 'digital-product-experience-v2', title: 'Digital Product Experience V2', categories: ['Art'] },
  { slug: 'digital-stickers', title: 'Digital Stickers', categories: ['Art'] },
  { slug: 'dog-memorial-ecards', title: 'Dog Memorial Ecards', categories: ['Animals'] },
  { slug: 'dogs-who-are-calm', title: 'Dogs Who Are Calm', categories: ['Animals'] },
  { slug: 'doll-house', title: 'Doll House', categories: ['Toys'] },
  { slug: 'double-dutch-bunch', title: 'Double Dutch Bunch', categories: ['Hobby'] },
  { slug: 'drone-display', title: 'Drone Display', categories: ['Entertainment', 'Services'] },
  { slug: 'elegant-french-restraurant', title: 'Elegant French Restraurant', categories: ['Food'] },
  { slug: 'entities-tax-structured-right', title: 'Entities Tax Structured Right', categories: ['Services'] },
  { slug: 'event-posters', title: 'Event Posters', categories: ['Events'] },
  { slug: 'exit-planners', title: 'Exit Planners', categories: ['Services'] },
  { slug: 'facing-tax-audit', title: 'Facing Tax Audit', categories: ['Services'] },
  { slug: 'facing-the-irs', title: 'Facing The Irs', categories: ['Services'] },
  { slug: 'fame-fabulous', title: 'Fame Fabulous', categories: ['Fame'] },
  { slug: 'fashion-centric', title: 'Fashion Centric', categories: ['Fashion'] },
  { slug: 'fast-food-tastes-good', title: 'Fast Food Tastes Good', categories: ['Food'] },
  { slug: 'fire-guard-prevention-services', title: 'Fire Guard Prevention Services', categories: ['Services'] },
  { slug: 'fit-body-fit-mind', title: 'Fit Body Fit Mind', categories: ['Fitness'] },
  { slug: 'football-time', title: 'Football Time', categories: ['Sports'] },
  { slug: 'frame-depot', title: 'Frame Depot', categories: ['Art', 'Hobby'] },
  { slug: 'free-fall-fever', title: 'Free Fall Fever', categories: ['Adventure'] },
  { slug: 'furniture-house', title: 'Furniture House', categories: ['Home'] },
  { slug: 'furniture-staging', title: 'Furniture Staging', categories: ['Services'] },
  { slug: 'game-sphere', title: 'Game Sphere', categories: ['Services'] },
  { slug: 'gardening-season', title: 'Gardening Season', categories: ['Hobby', 'Home'] },
  { slug: 'ghost-spectre-studios', title: 'Ghost Spectre Studios', categories: ['Holidays', 'Hobby', 'Mystical'] },
  { slug: 'gift-giving-surprise', title: 'Gift Giving Surprise', categories: [] },
  { slug: 'global-tax', title: 'Global Tax', categories: ['Services'] },
  { slug: 'graphic-stickers', title: 'Graphic Stickers', categories: ['Art'] },
  { slug: 'guitar-zero', title: 'Guitar Zero', categories: ['Art', 'Hobby'] },
  { slug: 'hair-inspiration', title: 'Hair Inspiration', categories: ['Hair'] },
  { slug: 'hair-ology', title: 'Hair Ology', categories: ['Hair'] },
  { slug: 'halloween-nights', title: 'Halloween Nights', categories: ['Holidays'] },
  { slug: 'happy-paw-ter', title: 'Happy Paw Ter', categories: ['Animals'] },
  { slug: 'haunted-houses', title: 'Haunted Houses', categories: ['Holidays', 'Hobby'] },
  { slug: 'height-lovers', title: 'Height Lovers', categories: ['Adventure'] },
  { slug: 'high-income-low-tax', title: 'High Income Low Tax', categories: ['Services'] },
  { slug: 'higher-altitude-wallpaper', title: 'Higher Altitude Wallpaper', categories: ['Hobby'] },
  { slug: 'holiday-calendars', title: 'Holiday Calendars', categories: ['Holidays'] },
  { slug: 'home-furnishings-galore', title: 'Home Furnishings Galore', categories: ['Home'] },
  { slug: 'home-sync', title: 'Home Sync', categories: ['Home', 'Services', 'Trending'] },
  { slug: 'horizon-tax-forecast', title: 'Horizon Tax Forecast', categories: ['Services'] },
  { slug: 'horses-free', title: 'Horses Free', categories: ['Animals'] },
  { slug: 'house-sitters', title: 'House Sitters', categories: ['Services'] },
  { slug: 'ice-sculture-smooth', title: 'Ice Sculture Smooth', categories: ['Art', 'Hobby'] },
  { slug: 'immersive-lab-studio', title: 'Immersive Lab Studio', categories: ['Services', 'Trending'] },
  { slug: 'innocent-spouse-relief-starts-now', title: 'Innocent Spouse Relief Starts Now', categories: ['Services'] },
  { slug: 'irs-crisis', title: 'Irs Crisis', categories: ['Services'] },
  { slug: 'irs-ligitation', title: 'Irs Ligitation', categories: [] },
  { slug: 'irs-installment-agreement-path', title: 'Irs Installment Agreement Path', categories: ['Services'] },
  { slug: 'irs-penalties-stopped', title: 'Irs Penalties Stopped', categories: ['Services'] },
  { slug: 'irs-transcript-clarity', title: 'Irs Transcript Clarity', categories: ['Services'] },
  { slug: 'jet-sky-adventures', title: 'Jet Sky Adventures', categories: ['Adventure', 'Lifestyle'] },
  { slug: 'jewelry-glam', title: 'Jewelry Glam', categories: ['Jewelry'] },
  { slug: 'kitchen-tips', title: 'Kitchen Tips', categories: [] },
  { slug: 'lake-wallpapers', title: 'Lake Wallpapers', categories: ['Art', 'Travel'] },
  { slug: 'language-translation', title: 'Language Translation', categories: ['Services'] },
  { slug: 'las-vegas-experience', title: 'Las Vegas Experience', categories: ['Services'] },
  { slug: 'life-insurance-benefits', title: 'Life Insurance Benefits', categories: ['Services'] },
  { slug: 'luxe-picnic', title: 'Luxe Picnic', categories: ['Lifestyle', 'Services', 'Trending'] },
  { slug: 'makeup-mile', title: 'Makeup Mile', categories: ['Beauty'] },
  { slug: 'mansion-top', title: 'Mansion Top', categories: ['Home', 'Lifestyle'] },
  { slug: 'millionniare-tax-insights', title: 'Millionniare Tax Insights', categories: ['Services'] },
  { slug: 'mini-home', title: 'Mini Home', categories: ['Home'] },
  { slug: 'motorcyle-touring', title: 'Motorcyle Touring', categories: [] },
  { slug: 'muscle-cars', title: 'Muscle Cars', categories: ['Cars'] },
  { slug: 'mystery-reveal-packages', title: 'Mystery Reveal Packages', categories: ['Adventure', 'Mystery'] },
  { slug: 'mystic-glow-wallpapers', title: 'Mystic Glow Wallpapers', categories: ['Art'] },
  { slug: 'neuro-peak', title: 'Neuro Peak', categories: ['Services', 'Trending'] },
  { slug: 'new-moms', title: 'New Moms', categories: [] },
  { slug: 'notary-today', title: 'Notary Today', categories: ['Services'] },
  { slug: 'notary-ready', title: 'Notary Ready', categories: ['Services'] },
  { slug: 'orb-flow-entertainment', title: 'Orb Flow Entertainment', categories: ['Entertainment'] },
  { slug: 'party-themes', title: 'Party Themes', categories: [] },
  { slug: 'payroll-times', title: 'Payroll Times', categories: ['Services'] },
  { slug: 'perfume-scent', title: 'Perfume Scent', categories: ['Beauty'] },
  { slug: 'photographers-delight', title: 'Photographers Delight', categories: [] },
  { slug: 'planet-portal', title: 'Planet Portal', categories: ['Cosmos'] },
  { slug: 'planet-pulse', title: 'Planet Pulse', categories: ['Cosmos'] },
  { slug: 'plot-twist', title: 'Plot Twist', categories: ['Adventure', 'Mystery'] },
  { slug: 'prompts-for-ai', title: 'Prompts For Ai', categories: [] },
  { slug: 'property-tax-advantage', title: 'Property Tax Advantage', categories: ['Services'] },
  { slug: 'quarterly-tax-planning-experts', title: 'Quarterly Tax Planning Experts', categories: ['Services'] },
  { slug: 'quilt-sewing-maker', title: 'Quilt Sewing Maker', categories: [] },
  { slug: 'rainbow-experience', title: 'Rainbow Experience', categories: ['Hobby'] },
  { slug: 'ramen-for-me', title: 'Ramen For Me', categories: ['Food'] },
  { slug: 'realtor-listing', title: 'Realtor Listing', categories: [] },
  { slug: 'retail-flip-sense', title: 'Retail Flip Sense', categories: [] },
  { slug: 'retire-smart', title: 'Retire Smart', categories: ['Services'] },
  { slug: 'roofing-experts', title: 'Roofing Experts', categories: ['Services'] },
  { slug: 'sales-tax-nexus', title: 'Sales Tax Nexus', categories: ['Services'] },
  { slug: 'salt-strategic-planner', title: 'Salt Strategic Planner', categories: ['Services'] },
  { slug: 'screen-visual-gallery', title: 'Screen Visual Gallery', categories: [] },
  { slug: 'segway-tours', title: 'Segway Tours', categories: ['Services'] },
  { slug: 'shark-attack', title: 'Shark Attack', categories: ['Animals', 'Hobby'] },
  { slug: 'sign-language-translation', title: 'Sign Language Translation', categories: ['Learning', 'Services'] },
  { slug: 'signal-and-scale', title: 'Signal And Scale', categories: ['Writing'] },
  { slug: 'sky-rise-balloon-adventure', title: 'Sky Rise Balloon Adventure', categories: ['Adventure'] },
  { slug: 'sneaker-ecards', title: 'Sneaker Ecards', categories: [] },
  { slug: 'soccer-wins', title: 'Soccer Wins', categories: [] },
  { slug: 'social-influencer', title: 'Social Influencer', categories: [] },
  { slug: 'space-layer-augmented-reality', title: 'Space Layer Augmented Reality', categories: ['Services'] },
  { slug: 'spinning-cards', title: 'Spinning Cards', categories: [] },
  { slug: 'stage-light-it-up', title: 'Stage Light It Up', categories: ['Services'] },
  { slug: 'stamps-in-digital', title: 'Stamps In Digital', categories: [] },
  { slug: 'stars-abound', title: 'Stars Abound', categories: ['Adventure'] },
  { slug: 'stay-scape', title: 'Stay Scape', categories: ['Destinations'] },
  { slug: 'sticker-drops', title: 'Sticker Drops', categories: [] },
  { slug: 'storage-here', title: 'Storage Here', categories: ['Home'] },
  { slug: 'street-racing-cars', title: 'Street Racing Cars', categories: ['Cars'] },
  { slug: 'stunt-core', title: 'Stunt Core', categories: ['Services'] },
  { slug: 'supercars', title: 'Supercars', categories: ['Cars'] },
  { slug: 'super-flyers', title: 'Super Flyers', categories: [] },
  { slug: 'sunsets-spectacular', title: 'Sunsets Spectacular', categories: ['Art', 'Photography'] },
  { slug: 'surfing-lounge', title: 'Surfing Lounge', categories: ['Sports'] },
  { slug: 'tarot-card-arcana', title: 'Tarot Card Arcana', categories: [] },
  { slug: 'tattoos-galore', title: 'Tattoos Galore', categories: [] },
  { slug: 'tax-attorney-services', title: 'Tax Attorney Services', categories: ['Services'] },
  { slug: 'tax-command-advisory', title: 'Tax Command Advisory', categories: ['Services'] },
  { slug: 'tax-credits-are-yours', title: 'Tax Credits Are Yours', categories: ['Services'] },
  { slug: 'tax-planning-today', title: 'Tax Planning Today', categories: ['Services'] },
  { slug: 'tax-preparation-now', title: 'Tax Preparation Now', categories: ['Services'] },
  { slug: 'tax-relief', title: 'Tax Relief', categories: ['Services'] },
  { slug: 'taxes-genz', title: 'Taxes Genz', categories: ['Services'] },
  { slug: 'tea-anyone', title: 'Tea Anyone', categories: ['Beverages'] },
  { slug: 'tea-dip-sip', title: 'Tea Dip Sip', categories: ['Beverages'] },
  { slug: 'the-daily-current', title: 'The Daily Current', categories: ['Writing'] },
  { slug: 'theme-ride-verse', title: 'Theme Ride Verse', categories: ['Entertainment'] },
  { slug: 'track-racing', title: 'Track Racing', categories: ['Cars'] },
  { slug: 'travel-meal-plan', title: 'Travel Meal Plan', categories: ['Food', 'Travel'] },
  { slug: 'tree-lovers-delight', title: 'Tree Lovers Delight', categories: ['Mood'] },
  { slug: 'trending-pulse', title: 'Trending Pulse', categories: ['Culture', 'Writing'] },
  { slug: 'trust-and-estate-planners', title: 'Trust And Estate Planners', categories: ['Services'] },
  { slug: 'unplug-retreat', title: 'Unplug Retreat', categories: ['Services', 'Trending'] },
  { slug: 'viral-moment', title: 'Viral Moment', categories: ['Social'] },
  { slug: 'virtual-persona-management', title: 'Virtual Persona Management', categories: ['Services', 'Trending'] },
  { slug: 'visual-strike-stickers', title: 'Visual Strike Stickers', categories: ['Art'] },
  { slug: 'vita-drip-mobile', title: 'Vita Drip Mobile', categories: ['Services', 'Trending'] },
  { slug: 'wall-paintings', title: 'Wall Paintings', categories: ['Art', 'Home'] },
  { slug: 'watches-superb', title: 'Watches Superb', categories: ['Jewelry'] },
  { slug: 'water-adventures', title: 'Water Adventures', categories: ['Adventure'] },
  { slug: 'wealth-shield-tax-strategies', title: 'Wealth Shield Tax Strategies', categories: ['Services'] },
  { slug: 'wedding-upgrade', title: 'Wedding Upgrade', categories: [] },
  { slug: 'weekend-adventure', title: 'Weekend Adventure', categories: ['Adventure'] },
  { slug: 'whale-breach', title: 'Whale Breach', categories: ['Animals'] },
  { slug: 'wild-weather', title: 'Wild Weather', categories: ['Weather'] },
  { slug: 'wild-weather-v2', title: 'Wild Weather V2', categories: ['Weather'] },
  { slug: 'windline-sailing', title: 'Windline Sailing', categories: ['Adventure'] },
  { slug: 'world-cuisine', title: 'World Cuisine', categories: ['Food'] },
  { slug: 'world-traveler', title: 'World Traveler', categories: ['Adventure'] },
  { slug: 'written-in-stone', title: 'Written In Stone', categories: ['Art'] },
  { slug: 'work-space-flow', title: 'Work Space Flow', categories: ['Trending'] },
  { slug: 'zoo-scape', title: 'Zoo Scape', categories: ['Adventure', 'Animals'] },
  { slug: 'ai-concierge-setup', title: 'Ai Concierge Setup', categories: [] },
  { slug: 'atlas-flip-co', title: 'Atlas Flip Co', categories: [] },
  { slug: 'aurora-glass-panels', title: 'Aurora Glass Panels', categories: [] },
  { slug: 'case-film-studio', title: 'Case Film Studio', categories: [] },
  { slug: 'charge-nest-installers', title: 'Charge Nest Installers', categories: [] },
  { slug: 'contrast-club-wellness', title: 'Contrast Club Wellness', categories: [] },
  { slug: 'cross-border-tax-partners', title: 'Cross Border Tax Partners', categories: [] },
  { slug: 'curio-cabinet-catalog', title: 'Curio Cabinet Catalog', categories: [] },
  { slug: 'cutaway-living', title: 'Cutaway Living', categories: [] },
  { slug: 'cutout-city-studio', title: 'Cutout City Studio', categories: [] },
  { slug: 'detail-zoom-atelier', title: 'Detail Zoom Atelier', categories: [] },
  { slug: 'draft-to-done-showcase', title: 'Draft To Done Showcase', categories: [] },
  { slug: 'exhibit-drop-gallery', title: 'Exhibit Drop Gallery', categories: [] },
  { slug: 'flow-grid-automation', title: 'Flow Grid Automation', categories: [] },
  { slug: 'folded-poster-studio', title: 'Folded Poster Studio', categories: [] },
  { slug: 'forecast-frame-studio', title: 'Forecast Frame Studio', categories: [] },
  { slug: 'gallery-shift-studio', title: 'Gallery Shift Studio', categories: [] },
  { slug: 'glass-elevator-one-pager', title: 'Glass Elevator One Pager', categories: [] },
  { slug: 'index-orbit-hub', title: 'Index Orbit Hub', categories: [] },
  { slug: 'ink-paper-editorial', title: 'Ink Paper Editorial', categories: [] },
  { slug: 'insight-forge-ai-analytics', title: 'Insight Forge Ai Analytics', categories: [] },
  { slug: 'lantern-alley-scroll', title: 'Lantern Alley Scroll', categories: [] },
  { slug: 'legacy-bridge-estate-advisory', title: 'Legacy Bridge Estate Advisory', categories: [] },
  { slug: 'lightbox-window', title: 'Lightbox Window', categories: [] },
  { slug: 'living-texture-lab', title: 'Living Texture Lab', categories: [] },
  { slug: 'map-room-explorer', title: 'Map Room Explorer', categories: [] },
  { slug: 'mini-vow-planner', title: 'Mini Vow Planner', categories: [] },
  { slug: 'mirror-corridor-reveal', title: 'Mirror Corridor Reveal', categories: [] },
  { slug: 'neon-blueprint-grid', title: 'Neon Blueprint Grid', categories: [] },
  { slug: 'neon-street-lookbook', title: 'Neon Street Lookbook', categories: [] },
  { slug: 'night-market-cards', title: 'Night Market Cards', categories: [] },
  { slug: 'night-train-narrative', title: 'Night Train Narrative', categories: [] },
  { slug: 'orbit-ring-catalog', title: 'Orbit Ring Catalog', categories: [] },
  { slug: 'paper-theatre-scroll', title: 'Paper Theatre Scroll', categories: [] },
  { slug: 'portal-look-beauty', title: 'Portal Look Beauty', categories: [] },
  { slug: 'poster-pulse-wall', title: 'Poster Pulse Wall', categories: [] },
  { slug: 'prism-catalog', title: 'Prism Catalog', categories: [] },
  { slug: 'quiet-authority-studio', title: 'Quiet Authority Studio', categories: [] },
  { slug: 'reel-ready-videos', title: 'Reel Ready Videos', categories: [] },
  { slug: 'rooftop-terrace-scroll', title: 'Rooftop Terrace Scroll', categories: [] },
  { slug: 'side-scroll-chapters', title: 'Side Scroll Chapters', categories: [] },
  { slug: 'skyline-time-code', title: 'Skyline Time Code', categories: [] },
  { slug: 'split-scene-studio', title: 'Split Scene Studio', categories: [] },
  { slug: 'stack-stage-one-pager', title: 'Stack Stage One Pager', categories: [] },
  { slug: 'studio-desk-story', title: 'Studio Desk Story', categories: [] },
  { slug: 'sunroom-bloom', title: 'Sunroom Bloom', categories: [] },
  { slug: 'texture-orchestra-atelier', title: 'Texture Orchestra Atelier', categories: [] },
  { slug: 'timeline-kinetic', title: 'Timeline Kinetic', categories: [] },
  { slug: 'vault-door-drop', title: 'Vault Door Drop', categories: [] },
  { slug: 'waterline-drift', title: 'Waterline Drift', categories: [] },
];

export function getCategoryLabel(categories: string[] | string | undefined): string {
  if (!categories) return 'business';
  const first = Array.isArray(categories) ? categories[0] : categories;
  return first ? first.toLowerCase() : 'business';
}
