import type { Metadata } from 'next';
import Script from 'next/script';
import Link from 'next/link';
import Header from '@/components/Header';
import DeadlineBanner from '@/components/DeadlineBanner';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Support — TaxClaim Pro',
};

const FAQ = [
  {
    q: 'What is the Kwong v. US ruling?',
    a: 'In 2023, the U.S. Court of Federal Claims ruled in Kwong v. United States that certain IRS penalties assessed between January 20, 2020, and July 10, 2023, may be challenged and refunded via IRS Form 843. This creates a limited but significant window for eligible taxpayers.',
  },
  {
    q: 'What is the filing deadline?',
    a: 'Claims must be filed by July 10, 2026. After this date, claims under the Kwong ruling cannot be reopened.',
  },
  {
    q: 'Is the preparation guide an official IRS form?',
    a: 'No. The guide generated by TaxClaim Pro is a PREPARATION GUIDE — NOT AN OFFICIAL IRS FORM. You must transfer the information to the official IRS Form 843, available at irs.gov/pub/irs-pdf/f843.pdf.',
  },
  {
    q: 'How do I get my IRS transcript?',
    a: 'Visit irs.gov/get-transcript or call 800-908-9946. Download or print your Account Transcript for the relevant tax years (2020–2023).',
  },
  {
    q: 'How much does TaxClaim Pro cost for tax professionals?',
    a: 'TaxClaim Pro is a flat $10/month for tax professionals. This gives you a fully branded subdomain page, unlimited client preparation guide generations, transcript upload, and submission tracking.',
  },
  {
    q: 'Can I cancel my subscription?',
    a: 'Yes. You can cancel any time from your dashboard. No setup fees or cancellation penalties.',
  },
];

export default function SupportPage() {
  return (
    <div className={styles.root}>
      <Script
        id="cal-init-general"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
(function (C, A, L) {
  let p = function (a, ar) { a.q.push(ar); };
  let d = C.document;
  C.Cal = C.Cal || function () {
    let cal = C.Cal; let ar = arguments;
    if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; }
    if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; if(typeof namespace === "string"){cal.ns[namespace] = cal.ns[namespace] || api; p(cal.ns[namespace], ar); p(cal, ["initNamespace", namespace]);} else p(cal, ar); return; }
    p(cal, ar);
  };
})(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init", "tax-claim-virtual-launch-pro", {origin:"https://app.cal.com"});
Cal.ns["tax-claim-virtual-launch-pro"]("ui", {"cssVarsPerTheme":{"light":{"cal-brand":"#292929"},"dark":{"cal-brand":"#f97316"}},"hideEventTypeDetails":false,"layout":"month_view"});
Cal("init", "tax-claim-virtual-launch-pro-support", {origin:"https://app.cal.com"});
Cal.ns["tax-claim-virtual-launch-pro-support"]("ui", {"cssVarsPerTheme":{"light":{"cal-brand":"#292929"},"dark":{"cal-brand":"#f97316"}},"hideEventTypeDetails":false,"layout":"month_view"});
`,
        }}
      />

      <DeadlineBanner />
      <Header showNav />

      <div className={styles.hero}>
        <div className={styles.heroInner}>
          <h1 className={styles.title}>Support Center</h1>
          <p className={styles.sub}>Get help with your TaxClaim Pro account or Form 843 preparation guide</p>
        </div>
      </div>

      <main className={styles.main}>
        {/* FAQ */}
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Frequently Asked Questions</h2>
          <div className={styles.faqList}>
            {FAQ.map((item) => (
              <details key={item.q} className={styles.faqItem}>
                <summary className={styles.faqQ}>{item.q}</summary>
                <p className={styles.faqA}>{item.a}</p>
              </details>
            ))}
          </div>
        </section>

        {/* Book a call */}
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Book a General Consultation</h2>
          <p className={styles.sectionSub}>Schedule a call with our team to discuss your Kwong claim strategy.</p>
          <div
            data-cal-namespace="tax-claim-virtual-launch-pro"
            data-cal-link="tax-claim-virtual-launch-pro"
            data-cal-config='{"layout":"month_view"}'
            className={styles.calEmbed}
          />
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Technical Support</h2>
          <p className={styles.sectionSub}>Need help with a specific issue? Book a support call.</p>
          <div
            data-cal-namespace="tax-claim-virtual-launch-pro-support"
            data-cal-link="tax-claim-virtual-launch-pro-support"
            data-cal-config='{"layout":"month_view"}'
            className={styles.calEmbed}
          />
        </section>

        {/* Useful links */}
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Helpful Links</h2>
          <ul className={styles.linkList}>
            <li>
              <a href="https://www.irs.gov/pub/irs-pdf/f843.pdf" target="_blank" rel="noopener noreferrer" className={styles.externalLink}>
                Official IRS Form 843 →
              </a>
            </li>
            <li>
              <a href="https://www.irs.gov/individuals/get-transcript" target="_blank" rel="noopener noreferrer" className={styles.externalLink}>
                Get Your IRS Transcript →
              </a>
            </li>
            <li>
              <Link href="/dashboard" className={styles.internalLink}>
                Your Dashboard →
              </Link>
            </li>
          </ul>
        </section>
      </main>
    </div>
  );
}
